version: "3"
services:
  model-api:
    build:
      context: .
    environment:
      - SERVER_PORT=3000
      - DATABASE_HOST=shared-postgres
      - DATABASE_NAME=postgres
      - DATABASE_USER=postgres
      - DATABASE_SCHEMA=public
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=postgres_password
      - NODE_ENV=development
#      - MOCK_JWT=true
    links:
      - shared-postgres
    volumes:
      - ./packages/server/lib:/home/node/app/lib:delegated
      - ./packages/database/lib:/home/node/app/node_modules/@capture-models/database/lib:delegated
      - ./packages/helpers/dist:/home/node/app/node_modules/@capture-models/helpers/dist:delegated
    ports:
      - 3000:3000

  shared-postgres:
    image: library/postgres:12
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres_password
    volumes:
      - ./var/shared-database:/var/lib/postgresql/data
    ports:
      - 35432:5432
