version: '3'
services:
  model-api:
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - SERVER_PORT=3000
      - DATABASE_HOST=shared-postgres
      - DATABASE_NAME=postgres
      - DATABASE_USER=postgres
      - DATABASE_SCHEMA=public
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=postgres_password
      - NODE_ENV=development
      - MOCK_JWT=true
    ports:
      - '3000:3000'
  shared-postgres:
    image: library/postgres:12
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres_password
    ports:
      - '35432:5432'
