name: Sync dependencies

on:
  schedule:
    # 03:00 each Saturday
    - cron: '0 3 * * 6'

  workflow_dispatch: {}

jobs:
  rebase:
    runs-on: ubuntu-latest
    steps:
      # Then checkout dependencies, this is branch we are rebasing.
      - uses: actions/checkout@v2
        with:
          ref: 'dependencies'
          fetch-depth: 0

      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout dependencies
          git rebase -s recursive origin/master
        continue-on-error: true

      - run: git push origin dependencies --force-with-lease
        continue-on-error: true
