name: Sync dependencies

on:
  schedule:
    # 03:00 each Saturday
    - cron: '0 3 * * 6'

  workflow_dispatch: {}

jobs:
  rebase:
    runs-on: ubuntu-latest
    steps:
      # Checkout master first, these are the commits we need.
      - uses: actions/checkout@v2
        with:
          ref: 'master'

      # Then checkout dependencies, this is branch we are rebasing.
      - uses: actions/checkout@v2
        with:
          ref: 'dependencies'

      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - run: git rebase -s recursive origin/master dependencies
        continue-on-error: true

      - run: git push origin dependencies --force-with-lease
        continue-on-error: true
