name: Sync dependencies

on:
  schedule:
    # 03:00 each Saturday
    - cron: '0 3 * * 6'

  workflow_dispatch: {}

jobs:
  rebase:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: 'dependencies'

      - name: Define git author for rebase
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - run: git rebase origin/master dependencies
      - run: git push origin dependencies --force-with-lease
