name: Update dependencies

on:
  push:
    branches:
      - dependencies

jobs:
  create_sync_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: dequelabs/action-sync-branches@v1
        with:
          head: dependencies
          base: master
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pr-title: '[Auto] Update all dependencies'
          pr-reviewers: stephenwf
